### ISSUE TITLE
貌似不工作了

### ISSUE THREAD

**Issue by justdark** [roylez/alfred_kuaidi#1]
貌似不工作了，你瞅瞅咋回事

**Comment by justdark** [comment]
ruby不会……我用python简单撸了一个 https://github.com/justdark/ExpressAlfredWorkflow
这种用到线上接口的一旦更新貌似就没法用了，能自动升级就好了，哈哈

**Comment by roylez** [comment]
这两天一直在潜心玩游戏，明天给看看吧。昨天用过记得还可以的，不过好像api那边反应变慢了

—
从 Mailbox 发送

**Comment by roylez** [comment]
今天试了下，还是可以正常使用的。

kuaidi100的网站改版了，如果开了firebug，就不能查询任何快递，我不知道用什么办法能够看到他们的js发送的request了。你如果有办法可以告诉我。目前来看只能凑合使用以前的request地址，如果他们更改api地址，我这里将无从获知。

—

**Comment by justdark** [comment]
http://www.kuaidi100.com/autonumber/auto?num=880046513239379439

http://www.kuaidi100.com/query?type=yuantong&postid=880046513239379439
我用的这两个，第一个查是什么快递，第二个查快递，就是直接用chrome的工具找到的

**Comment by roylez** [comment]
跟我这里用的没有差别

—
