### ISSUE TITLE
Alfred3 输入 kd 单号 不显示任何快递信息

### ISSUE THREAD

**Issue by xooooooooox** [roylez/alfred_kuaidi#11]
登录快递100网站，输入单号是有快递信息的，但 Alfred3 没有任何快递信息。

**Comment by TristenChenTao** [comment]
Alfred4 输入 kd 单号 也不显示任何快递信息

**Comment by foezzy** [comment]
快递接口被限制了，从单号去查快递公司这一步需要key，所以这个现在没法用了，几年前应该是可以的，再找别的吧

**Comment by roylez** [comment]
多谢提醒。

这个小项目能用这么几年也算是可以了。
