### ISSUE TITLE
12位的顺丰快递号无法查询

### ISSUE THREAD

**Issue by funabashi-cn-zz** [roylez/alfred_kuaidi#12]
为什么无法查询顺丰快递啊，12位快递号。说是什么验证码错误。

**Comment by roylez** [comment]
可以提供下快递号让我测试吗？

**Comment by detecti1** [comment]
我这里也遇到了同样的问题， 可以用这个单号做测试 `254412284165`
简单调查了一下，貌似快递100那边在查询顺丰件时要求输入收件人手机号后4位进行验证，所以提示查询错误

**Comment by roylez** [comment]
试过了。这不是目前可以绕过去的，起码不掏钱办不到。
