### ISSUE TITLE
不能工作了。

### ISSUE THREAD

**Issue by yxfish13** [roylez/alfred_kuaidi#2]
一输入貌似就自动挂了？是不是接口不行了

**Comment by roylez** [comment]
我这里没问题啊。

首先你确定下你用的是不是最新版本，如果不是，升级一下试试。

如果已经是最新版本，请在打开这个workflow的选项，点如图中的虫子按钮，再尝试查询，把log里面错误贴出来。

<img width="240" alt="screen shot 2016-03-26 at 16 41 49" src="https://cloud.githubusercontent.com/assets/62289/14058618/f02571e0-f371-11e5-8ecc-84704f961953.png">

**Comment by yxfish13** [comment]
早上突然挂了一会，之后就好了。。。
