### ISSUE TITLE
搜索结果一条太长时，怎么处理

### ISSUE THREAD

**Issue by agenttao** [roylez/alfred_kuaidi#8]
<img width="578" alt="qq20170721-084649 2x" src="https://user-images.githubusercontent.com/17685946/28444629-283f0302-6df1-11e7-95a8-3e3bbd12ed1f.png">
我想看派送人的信息，但是怎么都看不到，有没有什么解决办法

**Comment by roylez** [comment]
这个是Alfred的一个feature吧。事实上，我自己都不大清楚他怎么决定哪些文字省略的。不过你随时可以按Enter把整个状况复制下来。

或者，如果你觉得有用的话，我可以设成选中一个进度项，按回车，然后复制到剪切板和用notification center提示出来。你觉得行吗？

```
2017-07-21 07:44:32   [北京朝阳区定福庄公司]进行派件扫描；派送业务员：张子旺；联系电话：15100821949
2017-07-20 16:09:25   [北京分拨中心]从站点发出，本次转运目的地：北京朝阳区定福庄公司
2017-07-20 15:35:04   [北京分拨中心]在分拨中心进行卸车扫描
2017-07-19 21:45:48   [江苏淮安分拨中心]进行装车扫描，即将发往：北京分拨中心
2017-07-19 21:43:39   [江苏淮安分拨中心]在分拨中心进行称重扫描
2017-07-19 18:39:43   [江苏新沂市公司]进行揽件扫描
2017-07-19 18:26:40   [江苏新沂市公司]进行下级地点扫描，将发往：北京网点包
2017-07-19 18:11:50   [江苏新沂市公司]进行揽件扫描

```

**Comment by jtr109** [comment]
利用 Alfred 的 shift summary 会不会可以比较良好的解决显示问题?

就是 Alfred 搜索一般的 App 之类, focus 之后, 按 <kbd>Shift</kbd> 会显示对应信息.

没有实践经验, 只能提供一个建议供参考. @roylez

**Comment by roylez** [comment]
你用的是什么版本的Aflred？我现在还在用2.x，因为3.x的下开发的workflow不能在2.x用，但是2.x开发的3.x可以用。我这里按<kbd>Shift</kbd>不会有任何变化。

**Comment by jtr109** [comment]
哦, 可能因为我用的是3.x 的. 那可能需要其他方案了.

这是我按 <kbd>Shift</kbd>的样式, 可能是调用windows 的 preview 实现的.

![image](https://user-images.githubusercontent.com/13946679/28445846-9c55f5fe-6df9-11e7-9e0f-bafbda1166be.png)

**Comment by agenttao** [comment]
我是用的复制方法查看，我觉得shift预览不错，但是我的按下shift没反应，版本3.x

**Comment by jtr109** [comment]
作者用的是 2.x 所以好像没有 shift 功能, 首先你可以像我一样试试其他输入有没有这个功能, 比如 App 名称, 如果有, 说明这可能是 2.x 和 3.x 的一个差异.
目前这个插件是没有 shift 显示模式的, 因为作者没加呀. 不过他用的 2.x 如果是 2 和 3 的差异, 可能作者也无能为力了.

**Comment by roylez** [comment]
已经加上<kbd>Shift</kbd>提示了。现在也可以用<kbd>Enter</kbd>复制单条记录。

不过像上面的那种提升窗口，应该是调用了macOS的quick look，我暂时做不到。

**Comment by jtr109** [comment]
你好, 非常感谢你耗费时间精力为我们做的优化.

我刚刚下载并尝试了一下, 已经有 shift 和 enter 的相关提示. 但是不知道是不是和输入法冲突, 我点击 shift 的时候没有显示预览, 而是切换了输入法. 但是, 如果换成原生英文输入法([A]那个), 点击 shift 好像也没有弹窗或其他反映.

如果我能为你提供更多调试所需的信息, 也欢迎随时@我. 再次感谢.

![image](https://user-images.githubusercontent.com/13946679/29644437-9880f0ae-88a8-11e7-8478-d53990c80b27.png)

**Comment by roylez** [comment]
考虑到很多人用<kbd>Shift</kbd>切换输入法，我把提示改成<kbd>Ctrl</kbd>了。不过要显示哪一条的详情，就要先选中哪一条。弹窗那个我已经说过我这里没有办法。另外也可以用<kbd>⌘L</kbd>在屏幕上大字显示。

**Comment by jtr109** [comment]
下载尝试了一下, 非常完美!
